apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: frontend-golden-path
  namespace: frontend-golden-path
  name: pr-deploy-{{pr-number}}

spec:
  ingresses:
    - https://pr-deploy-{{pr-number}}.intern.dev.nav.no/
  image: {{image}}
  port: 8080